/**:
  platform:
    ros__parameters:
      nullparameter: "null"

drone0:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters

drone1:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: -2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters

drone2:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
