/**:
  platform:
    ros__parameters:
      nullparameter: "null"

drone0:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters

drone1:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: -2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters

drone2:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone3:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: -2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: -2.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone4:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: -2.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone5:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: -2.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone6:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: -2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 2.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone7:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 2.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone8:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 2.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone9:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: -2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 4.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone10:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 4.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters
drone11:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 2.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 4.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.0 # Initial z position of the vehicle in odometry frame. Meters